### 

POST https://whatsamplify.com/webhook/whatsapp-workflow/172558.195534.211071.1753514544 HTTP/1.1
Content-Type: application/json
Key: cricstock11@12

{
  "mobile": "918889981608",
  "otp": "123456"
}


### 

GET https://restapi.entitysport.com/exchange/matches/92263/info?token=8f3a13002d3b1e9a7f75013b4e86d2be HTTP/1.1


### 

GET https://restapi.entitysport.com/exchange/matches/?status=3&token=8f3a13002d3b1e9a7f75013b4e86d2be&pre_squad=true&per_page=50 HTTP/1.1


### 

GET https://restapi.entitysport.com/exchange/competitions?token=8f3a13002d3b1e9a7f75013b4e86d2be&per_page=616&&paged=1&status=result HTTP/1.1


### 

GET WS wss://webhook.entitysport.com:8087/connect?token=8f3a13002d3b1e9a7f75013b4e86d2be HTTP/1.1
