import mongoose from 'mongoose';

const liveMatchSchema = new mongoose.Schema({
  match_id: String,
  title: String,
  short_title: String,
  subtitle: String,
  match_number: String,
  format: String,
  format_str: String,
  status: String,
  status_str: String,
  status_note: String,
  verified: String,
  pre_squad: String,
  odds_available: String,
  game_state: String,
  game_state_str: String,
  domestic: String,

  competition: { type: Object },
  teama: { type: Object },
  teamb: { type: Object },
  venue: { type: Object },
  weather: { type: Object },
  pitch: { type: Object },
  toss: { type: Object },

  date_start: String,
  date_end: String,
  timestamp_start: String,
  timestamp_end: String,
  date_start_ist: String,
  date_end_ist: String,

  umpires: String,
  referee: String,
  equation: String,
  live: String,
  result: String,
  result_type: String,
  win_margin: String,
  winning_team_id: String,
  commentary: String,
  wagon: String,
  latest_inning_number: String,
  presquad_time: String,
  verify_time: String,
  match_dls_affected: String,
  day: String,
  session: String,
});

export default mongoose.model('LiveMatches', liveMatchSchema);